apiVersion: apps/v1
kind: Deployment
metadata:
  name: financas-cloud
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financas-cloud
  template:
    metadata:
      labels:
        app: financas-cloud
    spec:
      containers:
      - name: frontend
        image: ghcr.io/mpgaranito/tide-finance-vue:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 # <-- Mudou aqui para 3000
---
apiVersion: v1
kind: Service
metadata:
  name: financas-cloud-service
  namespace: default
spec:
  selector:
    app: financas-cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # <-- Mudou aqui para 3000 (O Service recebe na 80 e joga na 3000 do container)
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financas-cloud-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: financas.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: financas-cloud-service
            port:
              number: 80 # Mantém 80 aqui, porque o Service atende na 80